"""
Build script for creating a portable executable
Run this script to build the application as a standalone .exe file
"""
import subprocess
import sys
import os

def build_exe():
    """Build the executable using PyInstaller"""
    # Get the absolute path to the project root (where build.py is located)
    project_root = os.path.dirname(os.path.abspath(__file__))
    src_path = os.path.join(project_root, 'src')
    
    # Verify the version file exists
    version_file = os.path.join(src_path, '__version__.py')
    if not os.path.exists(version_file):
        print(f"ERROR: Version file not found at: {version_file}")
        print(f"Project root: {project_root}")
        print(f"Expected path: {version_file}")
        sys.exit(1)
    
    # Import version module explicitly
    import importlib.util
    spec = importlib.util.spec_from_file_location("__version__", version_file)
    version_module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(version_module)
    
    VERSION_STRING = version_module.VERSION_STRING
    APP_NAME = version_module.APP_NAME
    
    print("="*60)
    print(f"Building {APP_NAME}")
    print(f"Version: {VERSION_STRING}")
    print("="*60)
    
    # Verify version info file exists (will be generated by build.spec)
    version_info_path = os.path.join(project_root, 'version_info.txt')
    if os.path.exists(version_info_path):
        print(f"Version info file found: {version_info_path}")
    else:
        print(f"Note: Version info file will be generated during build")
    
    print("\nBuilding portable executable...")
    print("This may take a few minutes...")
    
    # Check if PyInstaller is installed
    try:
        import PyInstaller
    except ImportError:
        print("ERROR: PyInstaller is not installed.")
        print("Please install it by running: pip install pyinstaller")
        sys.exit(1)
    
    # Run PyInstaller with the spec file
    try:
        result = subprocess.run(
            ['pyinstaller', 'build.spec', '--clean', '--noconfirm'],
            check=True,
            cwd=os.path.dirname(os.path.abspath(__file__))
        )
        print("\n" + "="*60)
        print("Build completed successfully!")
        print("="*60)
        print(f"\nExecutable location: dist/ProjectLambdaLiveLogViewer-{VERSION_STRING}.exe")
        print("\nThe executable is portable and can be run on any Windows machine")
        print("without requiring Python or any dependencies to be installed.")
        print("="*60)
    except subprocess.CalledProcessError as e:
        print(f"\nERROR: Build failed with exit code {e.returncode}")
        sys.exit(1)
    except FileNotFoundError:
        print("ERROR: PyInstaller command not found.")
        print("Please ensure PyInstaller is installed and in your PATH.")
        sys.exit(1)

if __name__ == "__main__":
    build_exe()

